apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: openai-api-route
  namespace: price-runner
  annotations:
    gateway.envoyproxy.io/route-priority: "100"
spec:
  parentRefs:
  - name: bestai-gateway
    sectionName: http
  hostnames:
  - bestai.se
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /v1-mock
    backendRefs:
    - name: openai-api-service
      port: 3000
      weight: 100
